package com.summer.core.android.sms.mapper

import android.database.Cursor
import com.summer.core.android.sms.constants.SMSColumnNames
import com.summer.core.data.local.dao.SmsDao
import com.summer.core.data.local.entities.SmsEntity

object SMSMapper {

    val projection = arrayOf(
        SMSColumnNames.COLUMN_ID,
        SMSColumnNames.COLUMN_ADDRESS,
        SMSColumnNames.COLUMN_BODY,
        SMSColumnNames.COLUMN_DATE,
        SMSColumnNames.COLUMN_DATE_SENT,
        SMSColumnNames.COLUMN_TYPE,
        SMSColumnNames.COLUMN_THREAD_ID,
        SMSColumnNames.COLUMN_STATUS,
        SMSColumnNames.COLUMN_SERVICE_CENTER,
        SMSColumnNames.COLUMN_LOCKED,
        SMSColumnNames.COLUMN_PERSON,
        SMSColumnNames.COLUMN_READ,
        SMSColumnNames.COLUMN_SUBSCRIPTION_ID,
    )

    fun mapCursorToSmsList(
        cursor: Cursor?,
        smsDao: SmsDao,
        defaultCountryCode: Int
    ): List<SmsEntity> {
        val smsList = mutableListOf<SmsEntity>()

        cursor?.use {
            while (it.moveToNext()) {
                val sms = SmsEntity(
                    id = 0, // Auto-generated by Room
                    androidSmsId = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_ID)),
                    senderAddressId = smsDao.getOrInsertSenderId(
                        senderAddress = it.getString(
                            it.getColumnIndexOrThrow(
                                SMSColumnNames.COLUMN_ADDRESS
                            )
                        ).orEmpty(),
                        defaultCountryCode = defaultCountryCode
                    ),
                    rawAddress = it.getString(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_ADDRESS))
                        .orEmpty(),
                    body = it.getString(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_BODY))
                        .orEmpty(),
                    date = it.getLong(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_DATE)),
                    dateSent = it.getLong(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_DATE_SENT)),
                    type = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_TYPE)),
                    threadId = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_THREAD_ID)),
                    read = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_READ)),
                    status = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_STATUS)),
                    serviceCenter = it.getString(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_SERVICE_CENTER)),
                    subscriptionId = it.getInt(it.getColumnIndexOrThrow(SMSColumnNames.COLUMN_SUBSCRIPTION_ID)),
                    smsClassificationTypeId = null,
                    importanceScore = null,
                    confidenceScore = null,
                    createdAtApp = System.currentTimeMillis(),
                    updatedAtApp = System.currentTimeMillis()
                )
                smsList.add(sms)
            }
        }
        return smsList
    }
}